# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('Amount', models.FloatField()),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
